// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crdpgtkjyythfncbkcsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyZHBndGtqeXl0aGZuY2JrY3NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzg3MjAsImV4cCI6MjA2NDcxNDcyMH0.LmySbkhvz2QEu5eJBClToosGXdrfxbLoOQQQ6VmE2kg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);